services:
  - type: web
    name: alamin-hosting
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_DEBUG
        value: "0"